const db=wx.cloud.database()
Page({
 data:{months:[] as any[],total:'0.00',max:1,startMonth:'',endMonth:''}, onShow(){this.load()},
 setStart(e:any){this.setData({startMonth:e.detail.value});this.load()},setEnd(e:any){this.setData({endMonth:e.detail.value});this.load()},
 async load(){try{let q:any={};const c=db.command;if(this.data.startMonth&&this.data.endMonth)q.purchaseDate=c.gte(this.data.startMonth+'-01').and(c.lt(this.nextMonth(this.data.endMonth)));else if(this.data.startMonth)q.purchaseDate=c.gte(this.data.startMonth+'-01');else if(this.data.endMonth)q.purchaseDate=c.lt(this.nextMonth(this.data.endMonth));const r=await db.collection('purchases').where(q).orderBy('purchaseDate','asc').limit(1000).get();const map:any={};let total=0;(r.data as any[]).forEach(x=>{const m=x.purchaseDate.slice(0,7);map[m]=(map[m]||0)+x.amountCents;total+=x.amountCents});const keys=Object.keys(map).sort();const max=Math.max(1,...keys.map(k=>map[k]));const months=keys.map(k=>({month:k.slice(5)+'月',full:k,amount:(map[k]/100).toFixed(2),value:map[k]/100}));this.setData({months,total:(total/100).toFixed(2),max},()=>this.drawChart(months))}catch(e){console.error(e)}},
 nextMonth(m:string){const [y,mo]=m.split('-').map(Number);const d=new Date(y,mo,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`},
 drawChart(points:any[]){if(!points.length)return;const ctx=wx.createCanvasContext('trend');const w=340,h=210,left=36,right=12,top=22,bottom=34,max=Math.max(...points.map(x=>x.value),1);ctx.setStrokeStyle('#e8eaf0');ctx.setLineWidth(1);for(let i=0;i<4;i++){const y=top+(h-top-bottom)*i/3;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke()}const step=points.length>1?(w-left-right)/(points.length-1):0;ctx.setStrokeStyle('#5b55e7');ctx.setLineWidth(3);ctx.beginPath();points.forEach((p,i)=>{const x=points.length===1?w/2:left+step*i,y=top+(h-top-bottom)*(1-p.value/max);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();points.forEach((p,i)=>{const x=points.length===1?w/2:left+step*i,y=top+(h-top-bottom)*(1-p.value/max);ctx.setFillStyle('#5b55e7');ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.setFillStyle('#697184');ctx.setFontSize(10);ctx.setTextAlign('center');ctx.fillText(p.month,x,h-12)});ctx.draw()},
 home(){wx.navigateBack({delta:99})},records(){wx.redirectTo({url:'/pages/records/records'})},mine(){wx.redirectTo({url:'/pages/mine/mine'})},
})
